
server:
  port: 9090

resilience4j.circuitbreaker:
  instances:
    add:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpClientErrorException
      ignoreExceptions:
    get:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 2
      ringBufferSizeInHalfOpenState: 1
      waitDurationInOpenState: 10s
      failureRateThreshold: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

resilience4j.ratelimiter:
  instances:
    add:
      limitForPeriod: 5
      limitRefreshPeriod: 100000
      timeoutDuration: 1000ms

resilience4j.retry:
  instances:
    get:
      maxRetryAttempts: 1
      waitDuration: 50

resilience4j.bulkhead:
  instances:
    get:
      maxConcurrentCall: 10
      maxWaitDuration: 10ms

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true
